/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenampilgambar;

import java.awt.CardLayout;

/**
 *
 * @author LENOVO
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        GlassfishBTN = new javax.swing.JButton();
        JavaEEBTN = new javax.swing.JButton();
        PostgreSQLBTN = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        grassfishLB = new javax.swing.JLabel();
        postgressqlLB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GlassfishBTN.setText("Glassfish");
        GlassfishBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GlassfishBTNActionPerformed(evt);
            }
        });

        JavaEEBTN.setText("JavaEE");
        JavaEEBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JavaEEBTNActionPerformed(evt);
            }
        });

        PostgreSQLBTN.setText("PostgreSQL");
        PostgreSQLBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostgreSQLBTNActionPerformed(evt);
            }
        });

        ExitBTN.setText("Exit");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });

        imagePanel.setLayout(new java.awt.CardLayout());

        grassfishLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grassfishLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenampilgambar/1.jpg"))); // NOI18N
        imagePanel.add(grassfishLB, "0");
        grassfishLB.getAccessibleContext().setAccessibleName("0");
        grassfishLB.getAccessibleContext().setAccessibleDescription("null");

        postgressqlLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postgressqlLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenampilgambar/2.jpg"))); // NOI18N
        imagePanel.add(postgressqlLB, "1");
        postgressqlLB.getAccessibleContext().setAccessibleName("1");
        postgressqlLB.getAccessibleContext().setAccessibleDescription("null");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenampilgambar/3.png"))); // NOI18N
        imagePanel.add(jLabel1, "2");
        jLabel1.getAccessibleContext().setAccessibleName("2");
        jLabel1.getAccessibleContext().setAccessibleDescription("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(GlassfishBTN)
                .addGap(30, 30, 30)
                .addComponent(JavaEEBTN)
                .addGap(31, 31, 31)
                .addComponent(PostgreSQLBTN)
                .addGap(18, 18, 18)
                .addComponent(ExitBTN)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(imagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GlassfishBTN)
                    .addComponent(JavaEEBTN)
                    .addComponent(PostgreSQLBTN)
                    .addComponent(ExitBTN))
                .addGap(28, 28, 28)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void GlassfishBTNActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout()); 
        cl.show(imagePanel, "0");
    }                                            

    private void JavaEEBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout()); 
        cl.show(imagePanel, "1");
    }                                         

    private void PostgreSQLBTNActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout()); 
        cl.show(imagePanel, "2");
    }                                             

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        System.exit(0);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton GlassfishBTN;
    private javax.swing.JButton JavaEEBTN;
    private javax.swing.JButton PostgreSQLBTN;
    private javax.swing.JLabel grassfishLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel postgressqlLB;
    // End of variables declaration                   
}
